//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamedApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Balance = new HashSet<Balance>();
        }
    
        public int IdCurrency { get; set; }
        public string CurrencyName { get; set; }
    
        public virtual ICollection<Balance> Balance { get; set; }
    }
}
