//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamedApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Operation = new HashSet<Operation>();
        }
    
        public int IdTransaction { get; set; }
        public string TransactionName { get; set; }
    
        public virtual ICollection<Operation> Operation { get; set; }
    }
}
