//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamedApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int IdUserLogin { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual User User { get; set; }
    }
}
