//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YamedApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Balance = new HashSet<Balance>();
            this.Operation = new HashSet<Operation>();
        }
    
        public int IdUser { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthday { get; set; }
        public int IdGender { get; set; }
    
        public virtual ICollection<Balance> Balance { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Operation> Operation { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
